name: CI
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '00 04 * * 1' # 4am every Monday
  workflow_dispatch:

jobs:
  #
  # Fortran-side build and tests
  #
  build:
    name: Build, Test, Install
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: create build dir
      run: cmake -E make_directory build
    - name: build, test and install
      working-directory: build
      run: |
        cmake -DCMAKE_INSTALL_PREFIX="/tmp/libddx" ..
        make
        ctest -VV
        make install
    - name: test installation
      run: |
        mkdir /tmp/test
        mv ./cmake/testddXinstall.cmake /tmp/test/CMakeLists.txt
        cp ./tests/ddx_core.f90 /tmp/test/dd_core.f90
        cd /tmp/test
        mkdir build
        cd build
        cmake -G "Unix Makefiles" -DCMAKE_Fortran_COMPILER="gfortran-10" -DddX_DIR="/tmp/libddx/lib/ddX" ..
        make

  #
  # Python-side tests
  #
  python:
    name: Python tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - {os: ubuntu-latest}
          - {os: macos-11}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - uses: awvwgk/setup-fortran@main
        id: setup-fortran
        with:
          compiler: gcc
          version: 11
        if: contains( matrix.os, 'macos')
      - name: Install system dependencies on macOS
        run:  brew install ninja
        if: contains( matrix.os, 'macos')
      - name: Install python dependencies
        run: |
          python -m pip install --user wheel
          python -m pip install --user -r requirements.txt
      - name: Run python tests
        run: |
          python setup.py test
  #
  # Documentation
  #
  docs:
    needs: [build, python]
    name: Documentation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run Doxygen
      uses: mattnotmitt/doxygen-action@v1.9.4
    - name: Deploy documentation
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: doxygen/html
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
