name: CI
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '00 04 * * 1' # 4am every Monday
  workflow_dispatch:

jobs:
  build:
    name: Build, Test, Install
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: create build dir
      run: cmake -E make_directory build
    - name: build, test and install
      run: |
        cd build
        cmake -G "Unix Makefiles" -DCMAKE_Fortran_COMPILER="gfortran-10" -DCMAKE_INSTALL_PREFIX="/tmp/libddx" -DCMAKE_BUILD_TYPE=Release ..
        make
        ctest -VV
        make install
    - name: test installation
      run: |
        mkdir /tmp/test
        mv ./cmake/testddXinstall.cmake /tmp/test/CMakeLists.txt
        cp ./tests/ddx_core.f90 /tmp/test/dd_core.f90
        cd /tmp/test
        mkdir build
        cd build
        cmake -G "Unix Makefiles" -DCMAKE_Fortran_COMPILER="gfortran-10" -DddX_DIR="/tmp/libddx/lib/ddX" ..
        make
