name: Deploy documentation

on:
  push:
    branches:
      - main
  pull_request:
      branches:
          - main
  workflow_dispatch:

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Create build dir
      run: cmake -E make_directory build
    - name: Run cmake
      run: cmake ..
        working-directory: build
    - name: Run Doxygen
      run: make docs
        working-directory: build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/docs/html
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
